name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: bun ci

      - run: bun run format:check

      - run: bun run lint

      - run: bun run type-check

      - run: bun run build

      - run: bun run test

      - run: bun run test:e2e

  ci-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: bun ci

      - run: bun run type-check

      - run: bun run build

      - run: bun run test
